name: Minify CSS and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Minify CSS
        run: |
          mkdir -p dist/css
          npx clean-css-cli -o dist/css/style.min.css css/style.css
          cp -r img dist/
          cp *.html dist/
          cp sitemap.xml dist/

      - name: Replace CSS reference in HTML
        run: |
          for file in dist/*.html; do
            sed -i 's|css/style.css|css/style.min.css|g' "$file"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

